# Site
title: LHammer's Blog
author: LHammer
description: LHammer's Blog
keywords: hexo-theme, rexo, rtl, multilingual
language: zh-CN
favicon: /css/images/favicon.ico

url: https://lhammer.cn
theme_name: Rexo
theme_url: https://github.com/bluemix/hexo-theme-rexo

menu:
#  ğŸ : /
 ğŸ·: /tags/
#  ğŸ“—: /archives/
 ğŸ“Ÿ: /projects/
#  ğŸ: /photography/
 ğŸ‘¨ğŸ»â€ğŸ’»: /about/

# highlight
highlight:
  tomorrow

# Comment
comment:
    disqus: https-l-hammer-github-io


google_analytics: UA-119770326-1

about: 
  avatar: https://avatars2.githubusercontent.com/u/27677988?s=460&v=4
  description: ğŸ‘·æ¬ç –çš„FEå®ä¹ ç”Ÿ~
  long_description:
social:
  github: https://github.com/l-hammer
  github_username: l-hammer
  juejin: https://juejin.im/user/57a3dbb2d342d300574d8369
  juejin_username: LHammer
  twitter: https://twitter.com/lhammer_
  twitter_username: LHammer
  email: lhammering@gmail.com
  weixin: weixin-huiwu

# Customize
customize:
    sidebar: right # sidebar position, options: left, right or leave it empty

# miscellaneous:
#     links:
#       - link:
#         - Archive | Ø§Ù„Ø£Ø±Ø´ÙŠÙ
#         - /archives/
#         - ğŸ“—
#       - link: 
#         - Quotes | Ø­ÙƒÙ…
#         - /quotes/
#         - ğŸ“
#       - link: 
#         - Songs & Music | Ù…ÙˆØ³ÙŠÙ‚Ù‰ Ùˆ Ø£ØºØ§Ù†ÙŠ
#         - /music
#         - ğŸµ
#       - link: 
#         - Inspired by | Ø£Ø´Ø®Ø§Øµ Ø£Ø­Ø¨Ù‡Ù…
#         - /inspired
#         - ğŸ’–


